# Generated by Django 4.2.7 on 2023-12-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
